#!/bin/sh

# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	bat="cat /sys/class/power_supply/BAT?/capacity" \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	cls="clear" \
	mkd="mkdir -pv" \
  open="xdg-open" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner" \
	calcurse="calcurse -D ~/.config/calcurse"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
	la="exa --git -la" \
	ll="exa --git -l" \
	ka="killall" \
	abook="abook -C ${XDG_CONFIG_HOME:-$HOME/.config}/abook/abookrc --datafile ${XDG_CONFIG_HOME:-$HOME/.config}/abook/addressbook" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="sudo shutdown -h now" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	xi="sudo xbps-install -S" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	z="zathura" \

# This alias is important. It enables the `pauseallmpv` command.
alias mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)"

# Git alias
alias g="git" \
	gd="git diff" \
	gs="git status" \
	ga="git add" \
	gc="git commit -m" \
	gr="git reset" \
	gl="git log" \
	gpom="git push origin master"

# Some other stuff
alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/zshnameddirrc" \
	alsamixer="alsamixer; kill -44 $(pidof dwmblocks)" \
	wttr="curl wttr.in" \
	pbcopy="xclip -i" \
	pbpaste="xclip -o" \
	pwdcopy="pwd | xclip -i" \
	pwdpaste='cd `xclip -o`' \
	tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf" \
